
INSERT INTO lookup_account.banks (name, icon) values  
 ('Vietcombank', 'https://upload.wikimedia.org/wikipedia/en/thumb/e/e5/Vietcombank_Logo.png/220px-Vietcombank_Logo.png'),
 ('VietinBank', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/97/VietinBank_logo.png/220px-VietinBank_logo.png'),
 ('BIDV', 'https://upload.wikimedia.org/wikipedia/vi/thumb/f/fd/BIDV_Logo.svg/1200px-BIDV_Logo.svg.png'),
 ('Agribank', 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Agribank.svg/1200px-Agribank.svg.png'),
 ('Techcombank', 'https://upload.wikimedia.org/wikipedia/vi/5/52/Techcombank_Logo.png'),
 ('MB Bank', 'https://upload.wikimedia.org/wikipedia/vi/7/76/Logo_MBBank.png'),
 ('ACB', 'https://upload.wikimedia.org/wikipedia/vi/thumb/4/4f/Logo_ACB.svg/1200px-Logo_ACB.svg.png'),
 ('Sacombank', 'https://upload.wikimedia.org/wikipedia/vi/thumb/0/0e/Sacombank_logo.svg/1200px-Sacombank_logo.svg.png'),
 ('VPBank', 'https://upload.wikimedia.org/wikipedia/vi/6/62/VPBank_logo.png'),
 ('HDBank', 'https://upload.wikimedia.org/wikipedia/vi/1/13/Logo_HDBank.png'),
 ('SHB', 'https://upload.wikimedia.org/wikipedia/vi/f/f9/Logo_SHB.png'),
 ('VIB', 'https://upload.wikimedia.org/wikipedia/vi/2/2c/Logo_VIB.png'),
 ('LienVietPostBank', 'https://upload.wikimedia.org/wikipedia/vi/7/73/LienVietPostBank_logo.png'),
 ('SeABank', 'https://upload.wikimedia.org/wikipedia/vi/4/4d/Logo_SeABank.png'),
 ('Eximbank', 'https://upload.wikimedia.org/wikipedia/vi/e/e1/Eximbank_logo.png'),
 ('OCB', 'https://upload.wikimedia.org/wikipedia/vi/7/7d/Logo_OCB.png'),
 ('SCB', 'https://upload.wikimedia.org/wikipedia/vi/8/88/Logo_SCB.png'),
 ('ABBANK', 'https://upload.wikimedia.org/wikipedia/vi/1/1b/Logo_ABBank.png'),
 ('PVcomBank', 'https://upload.wikimedia.org/wikipedia/vi/8/88/PVcomBank_logo.png'),
 ('TPBank', 'https://upload.wikimedia.org/wikipedia/vi/thumb/4/4e/Logo_TPBank.svg/1200px-Logo_TPBank.svg.png'),
 ('Saigonbank', 'https://upload.wikimedia.org/wikipedia/vi/a/a3/Saigonbank_logo.png'),
 ('Bac A Bank', 'https://upload.wikimedia.org/wikipedia/vi/e/e8/Bac_A_Bank_logo.png'),
 ('Viet A Bank', 'https://upload.wikimedia.org/wikipedia/vi/1/18/Logo_VietABank.png'),
 ('Nam A Bank', 'https://upload.wikimedia.org/wikipedia/vi/8/8d/NamABank_logo.png'),
 ('Kienlongbank', 'https://upload.wikimedia.org/wikipedia/vi/6/60/Kienlongbank_logo.png'),
 ('MSB', 'https://upload.wikimedia.org/wikipedia/vi/4/48/Logo_MSB.png'),
 ('PGBank', 'https://upload.wikimedia.org/wikipedia/vi/9/91/PG_Bank_logo.png'),
 ('OceanBank', 'https://upload.wikimedia.org/wikipedia/vi/4/4b/OceanBank_logo.png'),
 ('VietBank', 'https://upload.wikimedia.org/wikipedia/vi/6/6b/Logo_VietBank.png'),
 ('DongA Bank', 'https://upload.wikimedia.org/wikipedia/vi/1/1b/Logo_DongABank.png'),
 ('PG Bank', 'https://upload.wikimedia.org/wikipedia/vi/9/91/PG_Bank_logo.png'),
 ('BaoVietBank', 'https://upload.wikimedia.org/wikipedia/vi/8/88/Logo_BaovietBank.png'),
 ('NCB', 'https://upload.wikimedia.org/wikipedia/vi/3/34/NCB_logo.png'),
 ('Public Bank Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/Public_Bank_Berhad_Logo.svg/1200px-Public_Bank_Berhad_Logo.svg.png'),
 ('Standard Chartered Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/c/c0/Standard_Chartered.svg/1200px-Standard_Chartered.svg.png'),
 ('Hong Leong Bank Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/5/5b/Hong_Leong_Bank_Logo.svg/1200px-Hong_Leong_Bank_Logo.svg.png'),
 ('Shinhan Bank Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/1/1e/Shinhan_Bank_logo.svg/1200px-Shinhan_Bank_logo.svg.png'),
 ('Woori Bank Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/8/89/Woori_Bank.svg/1200px-Woori_Bank.svg.png'),
 ('HSBC Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/HSBC_logo_%282018%29.svg/1200px-HSBC_logo_%282018%29.svg.png'),
 ('ANZ Vietnam', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/ANZ_Logo.svg/1200px-ANZ_Logo.svg.png'),
 ('Citibank Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/6/6c/Citibank.svg/1200px-Citibank.svg.png'),
 ('UOB Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/7/77/UOB_Logo.svg/1200px-UOB_Logo.svg.png'),
 ('DBS Bank Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/DBS_Bank_logo.svg/1200px-DBS_Bank_logo.svg.png'),
 ('Maybank Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Maybank_logo.svg/1200px-Maybank_logo.svg.png'),
 ('Bank of China (Vietnam)', 'https://upload.wikimedia.org/wikipedia/en/thumb/4/42/Bank_of_China_logo.svg/1200px-Bank_of_China_logo.svg.png'),
 ('Industrial Bank of Korea Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d8/Industrial_Bank_of_Korea_logo.svg/1200px-Industrial_Bank_of_Korea_logo.svg.png'),
 ('Mizuho Bank Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Mizuho_logo.svg/1200px-Mizuho_logo.svg.png'),
 ('Sumitomo Mitsui Banking Corporation Vietnam', 'https://upload.wikimedia.org/wikipedia/en/thumb/9/98/SMBC_Logo.svg/1200px-SMBC_Logo.svg.png')